import MiniSearch from 'minisearch';
import { allMeta } from '@/data/allMeta';

/**
 * Search v2 client (plan.md 8.0).
 *
 * The index is built from the static per-locale corpus generated by
 * scripts/gen_catalog_ns.py into public/search/{lng}.json and fetched lazily
 * on the first search interaction (sidebar focus or Ctrl-K). Corpora are
 * cached per language, so switching languages refetches at most once each.
 *
 * Indexed fields: name, slug, short (translated description), fns (function &
 * param identifiers from the entry data file), eip — full-text with prefix and
 * fuzzy matching ("swap" finds Uniswap entries, "royalty" finds ERC-2981).
 */

export interface SearchDoc {
  slug: string;
  name: string;
  eip: number | null;
  short: string;
  fns: string[];
  category: string;
  entryType: 'standard' | 'protocol';
}

/** A search result row: stored doc fields (fns are not stored). */
export interface SearchHit extends Omit<SearchDoc, 'fns'> {
  score: number;
}

type Index = MiniSearch<SearchDoc>;

const indexByLng = new Map<string, Index>();
const pendingByLng = new Map<string, Promise<Index>>();

function createIndex(): Index {
  return new MiniSearch<SearchDoc>({
    idField: 'slug',
    fields: ['name', 'slug', 'short', 'fns', 'eip'],
    storeFields: ['slug', 'name', 'short', 'category', 'entryType', 'eip'],
    searchOptions: {
      prefix: true,
      fuzzy: 0.2,
      boost: { name: 3, slug: 2, fns: 1.5 },
    },
    // "ERC-20", "erc20" and "erc 20" tokenize identically; camelCase fn names
    // stay whole so prefix search matches ("swapExact..." for "swap").
    tokenize: (text) =>
      text
        .toLowerCase()
        .split(/[\s\-_/()[\],]+/)
        .filter(Boolean),
    processTerm: (term) => term.toLowerCase(),
    extractField: (doc, fieldName) => {
      const value = doc[fieldName as keyof SearchDoc];
      if (Array.isArray(value)) return value.join(' ');
      return value == null ? '' : String(value);
    },
  });
}

/** Degraded corpus when the static file cannot be fetched (offline dev, etc.). */
function fallbackCorpus(): SearchDoc[] {
  return allMeta.map((m) => ({
    slug: m.slug,
    name: m.name,
    eip: null,
    short: '',
    fns: [],
    category: m.category,
    entryType: m.entryType,
  }));
}

async function fetchCorpus(lng: string): Promise<SearchDoc[]> {
  const response = await fetch(`/search/${encodeURIComponent(lng)}.json`);
  if (!response.ok) throw new Error(`search corpus ${lng}: HTTP ${response.status}`);
  return (await response.json()) as SearchDoc[];
}

/**
 * Resolve (fetch + build) the index for a language. Subsequent calls for the
 * same language are free; a language switch triggers one refetch.
 */
export function ensureSearchIndex(lng: string): Promise<Index> {
  const cached = indexByLng.get(lng);
  if (cached) return Promise.resolve(cached);

  const pending = pendingByLng.get(lng);
  if (pending) return pending;

  const promise = fetchCorpus(lng)
    .catch(async () => {
      // Unknown language code (e.g. regional variants) → try plain English
      // corpus before degrading to the meta-only fallback.
      if (lng !== 'en') {
        try {
          return await fetchCorpus('en');
        } catch {
          return fallbackCorpus();
        }
      }
      return fallbackCorpus();
    })
    .then((docs) => {
      const index = createIndex();
      index.addAll(docs);
      indexByLng.set(lng, index);
      pendingByLng.delete(lng);
      return index;
    });

  pendingByLng.set(lng, promise);
  return promise;
}

/** True when the index for the language is already built (no await needed). */
export function isSearchIndexReady(lng: string): boolean {
  return indexByLng.has(lng);
}

/** Search an already-built index; returns [] when it is not ready yet. */
export function searchSync(lng: string, query: string, limit = 12): SearchHit[] {
  const index = indexByLng.get(lng);
  const trimmed = query.trim();
  if (!index || !trimmed) return [];
  return index.search(trimmed).slice(0, limit) as unknown as SearchHit[];
}
