#!/usr/bin/env python3
"""Translation-memory manifest for the content batch pipeline (plan.md 8.2).

Tracks, per i18n namespace, which version (sha256) of the English source each
non-English locale file was translated against. This makes stale translations
mechanically detectable: when en/<ns>.json changes after a locale was stamped,
--check reports that locale file as STALE until it is re-translated and
re-stamped with --update.

Manifest:  i18n/translation-state.json   (repo root; committed)

Scope
  - Namespaces = src/i18n/locales/en/*.json, EXCLUDING 'catalog' (that file is
    generated by scripts/gen_catalog_ns.py, never hand-translated).
  - Locales   = zh-CN, zh-TW, ja, ko, es (en is the source of truth).

Hashing
  sha256 over the canonical JSON serialization of the parsed file
  (sort_keys=True, ensure_ascii=False, separators=(',', ':')), so the hash is
  stable across formatting / key order / line-ending churn and changes only
  when actual content changes.

Usage
    python scripts/gen_translation_state.py --update [--namespace NS ...]
        Stamp the CURRENT en hash as "translated against" for every namespace
        x locale pair (or only the listed namespaces). Run this immediately
        after a translation pass, when locales are known to match en.
        Also adds newly created namespaces and prunes deleted ones.

    python scripts/gen_translation_state.py --check [--strict] [--verbose]
        Compare recorded hashes against the working tree. Reports:
          STALE     locale was translated against an older en version
          UNTRACKED en namespace (or locale slot) not in the manifest yet
          MISSING   locale file recorded in the manifest but absent on disk
        Exit code: 0 unless --strict is given AND problems were found.
        Informational only (never fails): locale files edited since their
        last stamp (count always shown; per-file list with --verbose).

Typical batch flow (docs/authoring/batch-workflow.md):
    1. author + translate a batch
    2. python scripts/gen_translation_state.py --update
    3. CI / later batches run: gen_translation_state.py --check --strict
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOCALES_DIR = ROOT / "src" / "i18n" / "locales"
EN_DIR = LOCALES_DIR / "en"
STATE_PATH = ROOT / "i18n" / "translation-state.json"

TARGET_LOCALES = ["zh-CN", "zh-TW", "ja", "ko", "es"]

# Generated namespaces are never hand-translated -> never tracked here.
# 'catalog' is produced per-locale by scripts/gen_catalog_ns.py.
EXCLUDED_NAMESPACES = {"catalog"}

HASH_SPEC = "sha256(canonical-json: sort_keys, ensure_ascii=False, separators=(',',':'))"


def canonical_hash(path: Path) -> str:
    """sha256 of the canonical JSON serialization of *path* (see HASH_SPEC)."""
    try:
        obj = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"error: invalid JSON in {path.relative_to(ROOT)}: {exc}", file=sys.stderr)
        sys.exit(2)
    canonical = json.dumps(obj, sort_keys=True, ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def discover_namespaces() -> list[str]:
    if not EN_DIR.is_dir():
        print(f"error: missing en locale dir {EN_DIR}", file=sys.stderr)
        sys.exit(2)
    return sorted(
        p.stem for p in EN_DIR.glob("*.json") if p.stem not in EXCLUDED_NAMESPACES
    )


def load_state() -> dict:
    if not STATE_PATH.exists():
        return {"_meta": {}, "namespaces": {}}
    try:
        return json.loads(STATE_PATH.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        print(f"error: corrupt manifest {STATE_PATH.relative_to(ROOT)}: {exc}", file=sys.stderr)
        sys.exit(2)


def save_state(state: dict) -> None:
    STATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(state, indent=2, ensure_ascii=False, sort_keys=True)
    STATE_PATH.write_text(body + "\n", encoding="utf-8", newline="\n")


def cmd_update(only_namespaces: list[str] | None) -> int:
    namespaces = discover_namespaces()
    if only_namespaces:
        unknown = sorted(set(only_namespaces) - set(namespaces))
        if unknown:
            print(f"error: unknown namespace(s): {', '.join(unknown)}", file=sys.stderr)
            return 2
        to_stamp = sorted(only_namespaces)
    else:
        to_stamp = namespaces

    state = load_state()
    ns_state: dict = state.setdefault("namespaces", {})

    # Prune namespaces whose en file no longer exists (full-run only).
    if not only_namespaces:
        for gone in sorted(set(ns_state) - set(namespaces)):
            del ns_state[gone]
            print(f"pruned: '{gone}' (en/{gone}.json no longer exists)")

    stamped = 0
    missing: list[str] = []
    for ns in to_stamp:
        en_hash = canonical_hash(EN_DIR / f"{ns}.json")
        entry = ns_state.setdefault(ns, {})
        entry["enHash"] = en_hash
        locales_entry = entry.setdefault("locales", {})
        for lng in TARGET_LOCALES:
            locale_path = LOCALES_DIR / lng / f"{ns}.json"
            if not locale_path.exists():
                missing.append(f"{lng}/{ns}.json")
                locales_entry.pop(lng, None)
                continue
            locales_entry[lng] = {
                "translatedAgainst": en_hash,
                "localeHash": canonical_hash(locale_path),
            }
            stamped += 1

    state["_meta"] = {
        "generatedBy": "scripts/gen_translation_state.py",
        "hashAlgorithm": HASH_SPEC,
        "locales": TARGET_LOCALES,
        "updatedAt": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    save_state(state)

    print(
        f"stamped {stamped} locale file(s) across {len(to_stamp)} namespace(s) "
        f"-> {STATE_PATH.relative_to(ROOT)}"
    )
    if missing:
        print(f"warning: {len(missing)} locale file(s) missing on disk (not stamped):")
        for m in missing:
            print(f"  ! {m}")
        return 1
    return 0


def cmd_check(strict: bool, verbose: bool) -> int:
    namespaces = discover_namespaces()
    state = load_state()
    ns_state: dict = state.get("namespaces", {})

    stale: list[str] = []
    untracked: list[str] = []
    missing: list[str] = []
    locale_edited: list[str] = []

    for ns in namespaces:
        en_hash = canonical_hash(EN_DIR / f"{ns}.json")
        entry = ns_state.get(ns)
        if entry is None:
            untracked.append(f"{ns} (all locales)")
            continue
        for lng in TARGET_LOCALES:
            rec = entry.get("locales", {}).get(lng)
            locale_path = LOCALES_DIR / lng / f"{ns}.json"
            if rec is None:
                untracked.append(f"{lng}/{ns}.json")
                continue
            if not locale_path.exists():
                missing.append(f"{lng}/{ns}.json")
                continue
            if rec.get("translatedAgainst") != en_hash:
                stale.append(f"{lng}/{ns}.json")
            elif rec.get("localeHash") != canonical_hash(locale_path):
                locale_edited.append(f"{lng}/{ns}.json")

    orphaned = sorted(set(ns_state) - set(namespaces))

    problems = len(stale) + len(untracked) + len(missing) + len(orphaned)
    if stale:
        print(f"STALE ({len(stale)}) — en changed since these were translated:")
        for s in stale:
            print(f"  x {s}")
    if untracked:
        print(f"UNTRACKED ({len(untracked)}) — not in the manifest; run --update after translating:")
        for u in untracked:
            print(f"  ? {u}")
    if missing:
        print(f"MISSING ({len(missing)}) — recorded in manifest but absent on disk:")
        for m in missing:
            print(f"  ! {m}")
    if orphaned:
        print(f"ORPHANED ({len(orphaned)}) — in manifest but en file deleted (run --update to prune):")
        for o in orphaned:
            print(f"  - {o}")
    if locale_edited:
        print(f"info: {len(locale_edited)} locale file(s) edited since last stamp (not a failure)")
        if verbose:
            for e in locale_edited:
                print(f"  ~ {e}")

    total = len(namespaces) * len(TARGET_LOCALES)
    if problems == 0:
        print(f"OK: {len(namespaces)} namespaces x {len(TARGET_LOCALES)} locales ({total} files) up to date.")
        return 0
    print(f"\n{problems} problem(s) across {total} tracked slots.")
    return 1 if strict else 0


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Translation-memory manifest: track which en version each locale file was translated against.",
        epilog=(
            "examples:\n"
            "  python scripts/gen_translation_state.py --update\n"
            "  python scripts/gen_translation_state.py --update --namespace erc20 --namespace erc721\n"
            "  python scripts/gen_translation_state.py --check --strict\n"
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--update", action="store_true", help="stamp current en hashes as translated-against")
    mode.add_argument("--check", action="store_true", help="report stale/untracked/missing locale files")
    parser.add_argument(
        "--namespace",
        action="append",
        metavar="NS",
        help="(--update only) limit stamping to this namespace; repeatable",
    )
    parser.add_argument("--strict", action="store_true", help="(--check only) exit 1 when problems are found")
    parser.add_argument("--verbose", action="store_true", help="(--check only) list locale-edited files too")
    args = parser.parse_args()

    if args.update:
        return cmd_update(args.namespace)
    return cmd_check(strict=args.strict, verbose=args.verbose)


if __name__ == "__main__":
    sys.exit(main())
