#!/usr/bin/env python3
"""Generate src/data/allMeta.ts from src/data/catalog.json (plan.md 8.0).

Single source of truth
  - Standards:  src/data/catalog.json (owned by scripts/ingest_ercs.py; manual
                entries upserted by scripts/scaffold_entry.py). Only rows with
                published: true are emitted.
  - Protocols:  src/data/protocolsMeta.ts (hand-maintained) — merged into the
                generated file via a `...protocolsMeta` spread, so this script
                never rewrites protocol metadata.

Presentation curation (names / categories / sortOrder for the 22 pre-catalog
entries) lives in CURATED below: it is display-layer data that has no home in
the ingestion-owned catalog.json.

New published entries (post batch pipeline) default to:
  name = catalog title, category = 'utility' (TBD until authored),
  sortOrder = 10000 + eip (after all curated entries, ordered by EIP number).
NOTE: revisit the bare-title naming policy at content batch 01 if 'ERC-<n>'
style names are preferred for generated entries.

Usage
    python scripts/gen_allmeta.py [--no-prettier] [--check]

    --no-prettier  Skip the `npx prettier --write` formatting pass.
    --check        Exit 1 if the file on disk differs from what would be
                   generated (CI drift guard). Does not write.

Exit codes: 0 ok, 1 drift (--check) or validation problem.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = ROOT / "src" / "data" / "catalog.json"
ALL_META_PATH = ROOT / "src" / "data" / "allMeta.ts"

VALID_STATUSES = {"Draft", "Review", "Last Call", "Final", "Stagnant", "Withdrawn"}

HEADER = """\
// GENERATED by scripts/gen_allmeta.py — do not edit.
//
// Sources:
//   - standards: src/data/catalog.json (published rows only)
//   - protocols: src/data/protocolsMeta.ts (hand-maintained, spread below)
//
// Regenerate: python scripts/gen_allmeta.py
"""

# ─── Presentation curation for the pre-catalog entries ──────────────────────
# slug -> (name, category, sortOrder). Everything else derives from catalog.json.
CURATED: dict[str, tuple[str, str, int]] = {
    "erc20": ("ERC-20", "token", 100),
    "erc721": ("ERC-721", "nft", 200),
    "erc1155": ("ERC-1155", "nft", 300),
    "erc4626": ("ERC-4626", "token", 400),
    "erc2612": ("ERC-2612", "token", 500),
    "erc165": ("ERC-165", "utility", 600),
    "erc173": ("ERC-173", "utility", 700),
    "erc2981": ("ERC-2981", "nft", 800),
    "erc1967": ("ERC-1967", "proxy", 900),
    "erc1822": ("ERC-1822 (UUPS)", "proxy", 1000),
    "erc2535": ("ERC-2535 (Diamond)", "proxy", 1100),
    "erc4337": ("ERC-4337", "account", 1200),
    "erc6551": ("ERC-6551", "account", 1300),
    "erc7702": ("ERC-7702", "account", 1400),
    "erc1271": ("ERC-1271", "utility", 1500),
    "erc3525": ("ERC-3525 (SFT)", "token", 1600),
    "erc3643": ("ERC-3643 (T-REX)", "rwa", 1700),
    "erc5267": ("ERC-5267", "utility", 1800),
    "erc7683": ("ERC-7683", "cross-chain", 1900),
    "erc7579": ("ERC-7579", "account", 2000),
    "erc4361": ("ERC-4361 (SIWE)", "identity", 2100),
    "erc6900": ("ERC-6900", "account", 2200),
}

def ts_string(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def official_url(row: dict) -> str:
    # Unofficial / manual rows carry an explicit specUrl (ingest + scaffold set it).
    spec_url = row.get("specUrl")
    if spec_url:
        return spec_url
    if row.get("eip") is not None:
        return f"https://eips.ethereum.org/EIPS/eip-{row['eip']}"
    return "https://github.com/ethereum/ERCs"


def build_standard_block(row: dict) -> str:
    slug = row["slug"]
    curated = CURATED.get(slug)
    if curated:
        name, category, sort_order = curated
    else:
        name = row.get("title") or f"ERC-{row.get('eip')}"
        # siteCategory is written by scaffold_entry.py for manual rows; batch
        # authoring will supply it for generated rows. Default: TBD 'utility'.
        category = row.get("siteCategory") or "utility"
        sort_order = 10000 + (row.get("eip") or 0)

    lines = [
        "  {",
        f"    slug: {ts_string(slug)},",
        f"    name: {ts_string(name)},",
        f"    shortDescription: {ts_string(slug + '.short')},",
        f"    category: {ts_string(category)},",
        "    entryType: 'standard',",
        f"    officialUrl: {ts_string(official_url(row))},",
        f"    sortOrder: {sort_order},",
    ]
    status = row.get("status")
    if status in VALID_STATUSES:
        lines.append(f"    eipStatus: {ts_string(status)},")
    tier = row.get("tier")
    if tier in ("A", "B"):
        lines.append(f"    tier: {ts_string(tier)},")
    if row.get("unofficial"):
        lines.append("    unofficial: true,")
    lines.append("  },")
    return "\n".join(lines)


def generate() -> str:
    rows = json.loads(CATALOG_PATH.read_text(encoding="utf-8"))
    published = [r for r in rows if r.get("published")]

    slugs = [r["slug"] for r in published]
    dupes = {s for s in slugs if slugs.count(s) > 1}
    if dupes:
        print(f"ERROR: duplicate published slugs in catalog.json: {sorted(dupes)}", file=sys.stderr)
        sys.exit(1)

    def sort_key(row: dict) -> tuple[int, str]:
        curated = CURATED.get(row["slug"])
        order = curated[2] if curated else 10000 + (row.get("eip") or 0)
        return (order, row["slug"])

    blocks = [build_standard_block(r) for r in sorted(published, key=sort_key)]

    return (
        HEADER
        + "import type { ERCMeta } from './types';\n"
        + "import { protocolsMeta } from './protocolsMeta';\n\n"
        + "export const allMeta: ERCMeta[] = [\n"
        + "\n".join(blocks)
        + "\n  ...protocolsMeta,\n];\n"
    )


def run_prettier(path: Path) -> None:
    try:
        subprocess.run(
            f'npx prettier --write "{path.as_posix()}"',
            shell=True,
            check=True,
            cwd=ROOT,
            capture_output=True,
        )
    except (subprocess.CalledProcessError, OSError) as exc:
        print(f"WARNING: prettier pass failed ({exc}); file written unformatted.", file=sys.stderr)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate src/data/allMeta.ts from catalog.json")
    parser.add_argument("--no-prettier", action="store_true", help="skip prettier formatting")
    parser.add_argument("--check", action="store_true", help="fail if allMeta.ts is stale")
    args = parser.parse_args()

    content = generate()
    published_count = content.count("entryType: 'standard'")

    if args.check:
        current = ALL_META_PATH.read_text(encoding="utf-8") if ALL_META_PATH.exists() else ""
        if current != content:
            print("allMeta.ts is stale — run: python scripts/gen_allmeta.py", file=sys.stderr)
            sys.exit(1)
        print(f"allMeta.ts up to date ({published_count} published standards + protocolsMeta).")
        return

    with ALL_META_PATH.open("w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)
    if not args.no_prettier:
        run_prettier(ALL_META_PATH)
    print(
        f"Wrote src/data/allMeta.ts: {published_count} published standards"
        " + ...protocolsMeta spread."
    )


if __name__ == "__main__":
    main()
